<?php

/**
 * Events
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Events extends BaseEvents
{
      
  public static function getEventsListByDateQuery($timestamp, $users_id = null)
  {
    $q = Doctrine_Core::getTable('Events')
        ->createQuery()
        ->addWhere("'" . date('Y-m-d',$timestamp) . "' BETWEEN date_format(start_date,'%Y-%m-%d') AND date_format(end_date,'%Y-%m-%d')");
        
    if($users_id==null)
    {
      $q->addWhere('users_id is null or public_status = 1');
    }
    else
    {
      $q->addWhere('users_id =?',$users_id);
    }
    

    
    $q->orderBy('start_date'); 
    
    return $q->execute();    
  }
  
  
  public static function getEventsListByDate($timestamp, $users_id = null, $sf_user)
  {        
    $html = '';
                                                       
    foreach(Events::getEventsListByDateQuery($timestamp,$users_id) as $events)
    {                      
      $edit_action = '';
      
      if(($sf_user->hasCredential('public_scheduler_access_full_access') and $users_id==null) or ($sf_user->hasCredential('allow_manage_personal_scheduler') and $users_id>0))
      {
        $edit_action = 'onClick="openModalBox(\'' . url_for('scheduler/edit?id=' . $events->getEventId() . '&users_id=' . $users_id) . '\')"';
      }
      
      if($users_id==null and $events->getPublicStatus()==1)
      {
        $edit_action = '';
      }
      
      $event_name = '<a class="jt" href="#" onClick="return false" title="<b>' . __('Start Date'). ':</b> ' . app::dateTimeFormat($events->getStartDate()) . ' - <b>' . __('End Date'). ':</b> ' . app::dateTimeFormat($events->getEndDate()) . '" rel="' . url_for('scheduler/info?id=' . $events->getEventId()). '">' . $events->getEventName() . '</a>';
      
      $time = date('H:i',app::getDateTimestamp($events->getStartDate()));
      
      if($time!='00:00')
      {
        $event_name = $time . ' ' . $event_name;
      }
                                    
      $html .= '<div class="eventItem" ' . $edit_action . '>'  .  $event_name . '</div>';
            
    }            
               
    return $html;
  }
  
  public static function getCountTodaysEvents($users_id = null)
  { 
    return count(Events::getEventsListByDateQuery(mktime(0, 0, 0, date('m'), date('d'), date('Y')),$users_id));
  }
}